In [7]:
import numpy as np

In [8]:
# Python list
list = [1,2,3,4,5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
# NumPy array
arr = np.array([1,2,3,4,5])
print(list)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


In [10]:
# Creating a rank 1 Array
arr = np.array([1, 2, 3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 3 2]


In [13]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim)   # 2  (axes)
print(A.shape)  # (2, 3) dimension
print(A.size)   # 6  (total elements)
print(A.dtype)  # dtype('int64') (depends on system)
print(A.itemsize) # bytes per element

2
(2, 3)
6
int64
8


In [14]:
x = [j**4 for j in range(1,9)]
print(x)

%timeit x  #how much time take to excute x


[1, 16, 81, 256, 625, 1296, 2401, 4096]
27.7 ns ± 1.39 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [15]:
x = np.arange(1, 9) ** 4
print(x)
%timeit x  #how much time take to excute x

[   1   16   81  256  625 1296 2401 4096]
28.1 ns ± 1.03 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [16]:
#Dimensions in Arrays

#0-D Arrays
arr = np.array(42)

print(arr)

42


In [17]:
#1-D Arrays

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [18]:
#2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
#3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [21]:
#Check Number of Dimensions
x = np.array(42)
y = np.array([1, 2, 3, 4, 5])
z = np.array([[1, 2, 3], [4, 5, 6]])
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(x.ndim)
print(y.ndim)
print(z.ndim)
print(a.ndim)

0
1
2
3


In [23]:
#Higher Dimensional Arrays
# ndim used for any number of dimensions

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
