In [11]:
import numpy as np

In [12]:
# Python list
list = [1,2,3,4,5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [13]:
# NumPy array
arr = np.array([1,2,3,4,5])
print(list)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


In [ ]:
# Creating a rank 1 Array
arr = np.array([1, 2, 3],4,5)
print(arr)

[1 2 3]


In [16]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 3 2]


In [ ]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim)   # 2  (axes)
print(A.shape)  # (2, 3) dimension
print(A.size)   # 6  (total elements)
print(A.dtype)  # dtype('int64') (depends on system)
print(A.itemsize) # bytes per element

2
(2, 3)
6
int64
8


In [21]:
x = [j**4 for j in range(1,9)]
print(x)

%timeit x  #how much time take to excute x


[1, 16, 81, 256, 625, 1296, 2401, 4096]
28.7 ns ± 0.87 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [25]:
x = np.arange(1, 9) ** 4
print(x)
%timeit x  #how much time take to excute x

[   1   16   81  256  625 1296 2401 4096]
27.8 ns ± 0.972 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
