In [2]:
import numpy as np

In [3]:
# Python list
list = [1,2,3,4,5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
# NumPy array
arr = np.array([1,2,3,4,5])
print(list)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


In [5]:
# Creating a rank 1 Array
arr = np.array([1, 2, 3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 3 2]


In [8]:
A = np.array([[1,2,3],[4,5,6]])
print(A.ndim)   # 2  (axes)
print(A.shape)  # (2, 3) dimension
print(A.size)   # 6  (total elements)
print(A.dtype)  # dtype('int64') (depends on system)
print(A.itemsize) # bytes per element

2
(2, 3)
6
int64
8


In [9]:
x = [j**4 for j in range(1,9)]
print(x)

%timeit x  #how much time take to excute x


[1, 16, 81, 256, 625, 1296, 2401, 4096]
12.7 ns ± 0.229 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [10]:
x = np.arange(1, 9) ** 4
print(x)
%timeit x  #how much time take to excute x

[   1   16   81  256  625 1296 2401 4096]
12.8 ns ± 0.221 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [11]:
#Dimensions in Arrays

#0-D Arrays
arr = np.array(42)

print(arr)

42


In [12]:
#1-D Arrays

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [13]:
#2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
#3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
#Check Number of Dimensions
x = np.array(42)
y = np.array([1, 2, 3, 4, 5])
z = np.array([[1, 2, 3], [4, 5, 6]])
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(x.ndim)
print(y.ndim)
print(z.ndim)
print(a.ndim)

0
1
2
3


In [16]:
#Higher Dimensional Arrays
# ndim used for any number of dimensions

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [17]:
x=np.array([1,2,3])                 # from list
y=np.array([[1,2],[3,4]], dtype=float)
z=np.asarray([1,2,3])               # like array, avoids copy if already ndarray

print(x)
print(y)
print(z)

[1 2 3]
[[1. 2.]
 [3. 4.]]
[1 2 3]


In [19]:
#Ranges & evenly spaced
x=np.arange(0, 10, 2)               # [0 2 4 6 8]
y=np.linspace(0, 1, 5)              # [0. , 0.25, 0.5 , 0.75, 1. ]

# Log-spaced
z=np.logspace(1, 3, 3)              # [   10.   100.  1000.]

print(x)
print(y)
print(z)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  10.  100. 1000.]


In [20]:
#Filled arrays
x=np.zeros((2,3))                   # 2x3 zeros
y=np.ones((3,2), dtype=int)         # ones
z=np.full((2,2), fill_value=7.5)    # constant
a=np.empty((2,3))                   # uninitialized (whatever is in memory)

print(x)
print(y)
print(z)
print(a)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]
 [1 1]]
[[7.5 7.5]
 [7.5 7.5]]
[[3.47739925e-081 1.71630347e+185 2.63067650e-052]
 [1.52720859e+160 5.99138569e+174 1.78019082e-306]]
