In [11]:
import numpy as np

In [12]:
# Python list
list = [1,2,3,4,5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [13]:
# NumPy array
arr = np.array([1,2,3,4,5])
print(list)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>


In [ ]:
# Creating a rank 1 Array
arr = np.array([1, 2, 3],4,5)
print(arr)

[1 2 3]


In [16]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 3 2]
